project_id = "zkqwrhdcryxfkeneiqqd"

[functions.notify-low-stock-whatsapp]
verify_jwt = false

[functions.notify-encargo-status]
verify_jwt = false

[functions.notify-incident-status]
verify_jwt = false
